ruby '~>3.0.2'
source 'https://rubygems.org'

gem 'rake'
gem 'rspec'
gem 'nokogiri'
gem 'csl', '~>2.0'
gem 'fuubar'
gem 'csl-styles', git: 'https://github.com/adam3smith/csl-styles.git'
gem 'sheldon', git: 'https://github.com/citation-style-language/Sheldon.git'
