source 'https://rubygems.org'

gem 'rake'
gem 'rspec'
gem 'nokogiri'
gem 'csl', '~>1.0'
gem 'fuubar'
gem 'citeproc-ruby'
gem 'csl-styles'
gem 'diffy'
gem 'reverse_markdown'
gem 'octokit'
gem 'dotenv'
