name: Merge to release

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      commit_message:
        description: Commit message
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
    - uses: actions/checkout@v2
      if: github.event_name == 'push'
    - uses: actions/checkout@v2
      if: github.event_name == 'workflow_dispatch'
      with:
        fetch-depth: 0

    - name: Checkout release branch
      uses: actions/checkout@v2
      with:
        ref: 'v1.0.1'
        path: './release'

    - name: Check for relevant changes
      if: github.event_name == 'push'
      uses: dorny/paths-filter@v2
      id: release
      with:
        list-files: shell
        filters: |
          updated:
            - added|modified: [ '*.csl', '*.xml' ]
          deleted:
            - deleted: [ '*.csl', '*.xml' ]

    - name: Changed files
      if: github.event_name == 'push'
      run: |
        echo updated: ${{ steps.release.outputs.updated_files }}
        echo deleted: ${{ steps.release.outputs.deleted_files }}

    - name: Set up Ruby
      if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && (steps.release.outputs.updated == 'true' || steps.release.outputs.deleted == 'true'))
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: but use cache to speed that up
      if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && (steps.release.outputs.updated == 'true' || steps.release.outputs.deleted == 'true'))
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundle install
      if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && (steps.release.outputs.updated == 'true' || steps.release.outputs.deleted == 'true'))
      run: |
        bundle config path vendor/bundle
        bundle update sheldon --jobs 4 --retry 3

    - name: Populate new branch
      run: bundle exec sheldon --token=$GITHUB_TOKEN --verbose --populate release
      if: github.event_name == 'workflow_dispatch'

    - name: update the timestamps and add the changes
      run: bundle exec sheldon --token=$GITHUB_TOKEN --verbose --release release ${{ steps.release.outputs.updated_files }}
      if: github.event_name == 'push' && steps.release.outputs.updated == 'true'

    - name: delete deleted files
      run: cd release && git rm ${{ steps.release.outputs.deleted_files }}
      if: github.event_name == 'push' && steps.release.outputs.deleted == 'true'

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        repository: 'release'
        commit_message: Releasing ${{ steps.release.outputs.updated_files }} ${{ steps.release.outputs.deleted_files }}
      if: github.event_name == 'push' && (steps.release.outputs.updated == 'true' || steps.release.outputs.deleted == 'true')

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        repository: 'release'
        commit_message: ${{ github.event.inputs.commit_message }}
      if: github.event_name == 'workflow_dispatch'
